[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
candle-core = "0.8.2"
candle-nn = "0.8.2"
candle-transformers = "0.8.2"
hf-hub = "0.4.1"
polars = { version = "0.46.0", features = ["lazy", "parquet", "cloud"] }
